# If you want to activate file-based configuration with config_suite:
# copy this file "services.config.yml".
services:
  # File-based configuration.
  config.storage:
    class: Drupal\Core\Config\CachedStorage
    arguments: ['@config.storage.active', '@cache.config']
  config.storage.active:
     class: Drupal\Core\Config\FileStorage
     factory: Drupal\Core\Config\FileStorageFactory::getActive
