version: 1
update_configs:
- package_manager: "php:composer"
  directory: "/"
  update_schedule: "daily"
  allowed_updates:
  - match:
      dependency_name: "united-philanthropy-forum/km_collaborative"
